### ISSUE TITLE
generate type / spec Go code when spec is nil

### ISSUE THREAD

**Issue by bradrydzewski** [drone/spec#12]
`abort` and `ignore` types do not have a spec, however, the current Go code generator requires a target spec for all objects. Update the code generation to support this use case and then remove the `failure_abort` and `failure_ignore` schemas

```
oneOf:
- allOf:
  - properties:
      type:
        const: abort
  - properties:
      spec:
        $ref: ./failure_abort.yaml
- allOf:
  - properties:
      type:
        const: ignore
  - properties:
      spec:
        $ref: ./failure_ignore.yaml
```
